version: "3.9"

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=schooldb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5431:5431"

  web:
    container_name: web
    restart: always
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=schooldb
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - memcached

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
